### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by ermin-cahtarevic**
We think that we finished the project, we followed the requirements from the Pathwright and the sample page. We are requesting a code review so we can merge it to the master branch.

### CODE REVIEW

**Comment by KaushikShivam** [comment]
## Pull Request under the review by Shivam Kaushik

**Review by KaushikShivam — CHANGES_REQUESTED** [review]
# Changes Required 😈 

Hello, @ermin-cahtarevic & @mcastorena0316 👋 
Awesome job on building your very first project!! Well done!

However, there are a couple of things that are missing that I'd like you to do for completion.

## Mandatory changes
1. Navigation Bar
    - [ ] It should have at least three embedded images on the rightmost part of the navbar that represents icons and/or an avatar. I see that you've used font-awesome instead but the aim of this project is to practice embedding images.

2. Use of semantic tag
    - [ ] Use the ```<main>``` tag for your dominant content inside the ```body``` tag instead of a ```div```.

3. Live version
     - [ ] Please add a live version of the website and include it in your README.

## Optional changes

These changes are suggested to make your repo look more professional.
1. [OPTIONAL] Descriptive README
    As I see, you've have a descriptive README file. However, you could make use of markdown to give more structure to the file. You can use this [tutorial](https://guides.github.com/features/mastering-markdown/) for reference. Things you can consider adding to your readme:
     - [ ] Author names and contact info
     - [ ] Live version of the website
     - [ ] Reference link of the youtube page and project guidelines
2. [OPTIONAL] Try to make your design look as close to the reference link as possible. These are the projects that you'll add to your portfolio and they should look the best. 😄 

 ### That's all, guys! 
**Make these changes and submit for a code review, again**
This is your first project and you guys have done exceptionally well. I'm sure these changes won't take you much time. 👍 

**If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**

Happy coding! 😄 
[Shivam Kaushik](https://github.com/KaushikShivam)
[Github](https://github.com/KaushikShivam) [Twitter](https://twitter.com/kShivamDev) [Linkedin](https://www.linkedin.com/in/shivam-kaushik-bb8162102/)

**Comment by ermin-cahtarevic** [comment]
We fixed all the mandatory issues that were stated by the previous code reviewer. We chenged the README file, changed the icons to embedded images and changed the div to a main.

**Review by uche-inyama — APPROVED** [review]
## Hi team,

Nicely done, you have implemented the required changes. But before you merge I would like to suggest few things:

- [ ] The link to the live version of your project in the README.md file, should wrapped nicely with a markdown syntax for presenting links in github. Go through this [link](https://guides.github.com/features/mastering-markdown/), it won't take long.

- [ ] Also, add a ```<footer> tag``` to wrap up the  footer section of your html document.

- [ ] In your next project, use [font awesome](https://fontawesome.com/) for your icons :slightly_smiling_face:

#### ``` Have a great day ``` :slightly_smiling_face: 

@ Uchechukwu Henry Inyama

**Comment by ermin-cahtarevic** [comment]
Hi,
We just implemented the changes, but we were using font-awesome icons before also. And now do we need to submit another code review form, or complete the project?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
